### ISSUE TITLE
Barcode validation

### ISSUE THREAD

**Issue by DavisGoglin** [python-escpos/python-escpos#100]
There is a list of allowed data and barcode sizes in the [epson documentation](https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=128). We should be validating data length and content. 

A short term solution would be to set up regexes similar to [escpos-php here](https://github.com/mike42/escpos-php/blob/0365deee8591ac5e80f748dce06bf0082ea59833/src/Mike42/Escpos/Printer.php#L201), but in the future we might want to see if there is an external barcode library to validate checksums.

**Comment by patkan** [comment]
So far I have found https://pypi.python.org/pypi/pyBarcode/0.7
This is, however, a library for image generation. (We could use it in order to generate barcodes on models that do not support barcode-printing)

**Comment by Loafdude** [comment]
Should python-escpos venture beyond the escpos protocol? I think it's better to focus.
There are lots of libraries that can create barcodes. We should leave that up to the user.
As long as we can print, position and handle PIL objects I think we are good.

We should definitely do character set and length checking.

I have a barcode scanner handy here and most of the barcodes scanned fine. 

I think the printer is doing checksum for us?
Ill try and decode some manually and check

**Comment by Loafdude** [comment]
Okay after quick review of UPC-A
escpos spec says you can supply 11 or 12 character data.

UPC-A spec requires 12 digits.
if 11 digits my printer calculates the check digit. 
if 12 digits my printer prints the supplied 12th character check digit.
this is the best of both worlds I'd say.

a very quick look at code 128 with both my smartphone and usb scanner seems to indicate the checksum is calculated

Considering all the barcodes in my test scanned I would say the printer is supposed to handle the checksum for us.

So my conclusion is if a user wants to supply their own checksum they simply pass it, otherwise it is calculated by the printer.
That said, maybe non-epson stuff doesnt work this way?
Regardless we shouldn't write escpos to a specific printer but keep it generic.
If a user's printer does not support checkdigit calculation than they will need to do it in their own code.
Perhaps you guys can check your printers to observe their behavior.

I used
    e.text("UPC-A\n")
    e.barcode('13243546576','UPC-A',function_type="A")
    e.text("UPC-A\n")
    e.barcode('132435465767','UPC-A',function_type="A")

the first should scan. (check digit printed is 2)
The second should not (check digit 7 is invalid)

regex on character set and length should be sufficient I'd say.

**Comment by DavisGoglin** [comment]
I'll test it out when I get to my printer. My main worry was passing invalid barcode data and having the printer output text instead of a barcode. It looks like regex will cover most or all of that.

**Comment by patkan** [comment]
@Loafdude you are probably right, we should stay rather tight with our features. At least as long as there are still problems like cases in which image-printing does not work.

I tried the code and can confirm: the first UPC-A scans correctly and the second one does not.

**Comment by mike42** [comment]
Basically echoing the above- The regexes used to validate barcode data in [escpos-php](https://github.com/mike42/escpos-php) don't mind whether the checksums are valid, they were just added to avoid the creation of invalid ESC/POS.

I think that a well-behaved driver should avoid sending things that the device is not likely to understand. This is also useful for debugging (eg. in mike42/escpos-php#113, an exception was thrown when the CODE128 encoding was not included).

Some more info about barcodes that I've got from the PHP driver-
- The open source Android app [zxing/zxing](https://github.com/zxing/zxing) is excellent for verifying printed barcodes.
- This example ([PHP](https://github.com/mike42/escpos-php/blob/7029b7bdc5b79dbfc81c2364720187b671e53be7/example/barcode.php), [binary ESC/POS blob](https://github.com/mike42/escpos-php/raw/56afef6601a702b152c7fef8ee992a9cc383bf9d/test/integration/resources/output/barcode.bin)) prints a receipt containing a variety of barcode types.
- I'm planning to write feature requests up for escpos-php shortly to add-
 - a wrapping function for each of the nine types of barcode, accepting the data as one paramater, and any type-specific options as the other parameters, so that the driver does not expose how the barcode data is represented in ESC/POS.
 - image-based fallback for printers that can't handle barcodes themselves.

**Comment by MicroJoe** [comment]
Exploring the viivakoodi code I have found a `check_code` function that is called upon every code creation (code39, code128...) and that can check the passed characters are correct. See https://github.com/kxepal/viivakoodi/blob/b8a1f90242d87e8c72f0200747763b7c79ccbab0/barcode/codex.py#L20

We may want to construct viivakoodi barcodes even before hardware barcode sending for verifications purpose by using the viivakoodi validation knowledge. If the code is incorrect we can catch the exception, and if the code is correct then constructor ends fine and we can continue hardware printing of the code.

**Comment by MicroJoe** [comment]
Hello there. Since #255 got merged, may we close this issue? Good work on the PR btw!

**Comment by patkan** [comment]
As far as I see it, yes. Thanks for the notification.
If anyone thinks differently, as always, please comment :-)
