### ISSUE TITLE
Status Commands 

### ISSUE THREAD

**Issue by grs47** [python-escpos/python-escpos#143]
### Problem

I am trying to read status from a Usb connected esc/pos printer, and it always returns array('B',[0]) or behaves awkwardly (blocks until physical usb disconnect) with timeout expections of libusb1 if I try to send a third argument on device.write or device.read. I don't understand the "interface" parameter to the Usb construction, and its usage as a third argument on device.write, it makes no sense according to pyUsb docs, where it states it should be a timeout. 
### Steps to reproduce
- Remove paper from printer.
- Define the printer e = Usb(0x0XXX,0x0YYY)
- msg=b'\x10\x04\x04'. _DLE EOT 4- Paper Sensor, 8bits, 5 and 6th should  be 1 when paper end_
- e.device.write(e.ep_out, msg)
- e.device.read(e.ep_out,1)
### Device info

 **Printer:** EPSON TM20-II

 **python-escpos version:** 2.0.0

**Comment by patkan** [comment]
Thank you for the issue!
I am sorry, but I did not yet touch the USB-code, because I have no compatible device at hand. But you are right, as far as I read the spec of pyUSB, setting the interface is completely wrong at this point. (I would have to investigate further, but maybe this originated from improper migration from older libusb-versions)

Reading the status is something that I would like to have for every printer, but I fear I can't help you that much at the moment.
Just for clearity: "normal" printing with the library does work? (So that we can assume that writing to the device works correctly.)

**Comment by grs47** [comment]
I have been scavaging a bit but I did not yet understand where the problem lies. I know some esc-pos perl wrapper by other guy gives Status! He uses bulk reading and writting more explicity in his code. This PyUSB thing abstracts stuff. Anyway, If I try to write or read in a status error (e.g. remove paper) he will give libusb1.py 110 timeout error. Suposedly we should be able to read status even when the printer is offline! I guess all this middle things are hiding the connection. If I can do anything to help please say. I will still try to find a way around it.

Yes I can print text and images. This updated version (2.0.0) is really fast with images!  Thanks for your work.

**Comment by patkan** [comment]
You are welcome! (However, the image printing is not my work ;-) )
I will keep an eye open and as soon as I get to it, I will read through the pyUSB-tutorial in detail.
Maybe I (or someone else) have the time to implement the status reading for the serial-printer. This way we can compare the behaviour and maybe get closer to a solution.

**Comment by grs47** [comment]
I think I am figuring something out. Check quick reference commands here: https://download.epson-biz.com/modules/pos/index.php?page=single_doc&cid=3723&dcat=27&pcat=3

**Note:** This is tested in Epson TM20-II

### Reading status paper steps:
- e = Usb(0x04b8,0x0e15)
- e.device.write(e.out_ep, ''\x10\x04\x04", 5000) # 5 second timeout, in miilseconds, DLE EOT n=4 esc/pos command
- e.device.read(e.in_ep, 256,5000)
- e.close()

###Result interpreting:
The read will return either Array ('B', [114]) or Array ('B', 18])  if you do not have or have paper in the printer, respectively. Turning 114 and 18 into binary, this makes sense, as the 5th and 6th bits should be 1 when we are in paper end, and 0 when we are in paper present. However, nothing in the manual refers to the first or the forth bit being always 1. Eitherways, these bits never take part in status, so I guess it is working. 

I also tried with DLE EOT 2 command with the paper door opened and I'm not sure if it is right. Results were 22 with door open and 18 with door closed: door bit (second) coming at 1 when it is open but sixth bit (error state) is zero. Maybe error state is something else (as by n=3 quick reference)

**Note** , you can only read that number once. To read status again, you must close and reopen the usb connection.

**Comment by DavisGoglin** [comment]
The rest of the bits are described in the epson ESC/POS manual on the DEL EOT page [here](https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=118). 

But I don't see any reason why you'd have to make a new connection after a status check. If my printer supports status I'll see what networked mode does. 

We will need to make some status functions. I promise I'm alive and still interested in working on this project!

**Comment by grs47** [comment]
Well when I am in status error, I can only make one correct status read per connection. Pretty wierd stuff. If I insist, usb.core.USBError 110 (timeout) will occur.

**Comment by patkan** [comment]
Maybe we can use this as an aid: https://github.com/fvdsn/py-xml-escpos/blob/master/xmlescpos/printer.py
(However, I would move the function for querying the status into Escpos)

**Comment by mike42** [comment]
@grs47 I think I've also seen the "one status query per connection" issue on a TM-T20II, where I've had to power cycle the printer to get it online again after `DLE EOT`. I'm using [this PHP code](https://github.com/mike42/escpos-php/blob/f6bb510e6f3668ae278d7aec3afb029104e1459f/src/Mike42/Escpos/Printer.php#L580) to send commands via `usblp` (which holds the interface open and presents it as a file), so I think we can be quite certain that this is a printer quirk, and not `python-escpos` causing trouble.

In any case, if re-opening the USB connection works for you, then there might be hope for this on your printer.

**Comment by MeritEhab** [comment]
@grs47 @patkan 

Sorry guys for commenting on this after issue is closed but I can'r figure out how to use the paper_status command

could anyone please put a snip of the code that made a usb or network printer and call paper status ? or maybe put it in the examples  files anywhere is fine 

Thanks in advance

**Comment by shehanGuruge** [comment]
Hi @grs47 and @anyone,

I would love to hear some clarification on the above response since I am also getting the same response and got no idea of decoding it to get an actual answer. Lets say i am receiving 114 when I have removed the paper roll from the printer, so the 8 bits binary would be 01110010. According to the guide below,
<img width="609" alt="Screenshot 2023-03-08 at 10 04 00" src="https://user-images.githubusercontent.com/39302321/223620435-27b545ae-de70-406c-8d9e-6053e75b1fc9.png">

2nd bit needs to be 0 which symbolizes paper present, while 3rd bit needs to be 1 which detects the paper end. So in the above binary 2nd bit is 1 and 3rd bit is also 1, which means there is no adequate paper (if i am not wrong). But when we consider the 5th and the 6th bits, 
  5th bit = 0 
  6th bit = 1

So when we consider with the above table, 5th bit means paper is present when 0, while 6th bit means paper roll end when 1,  it doesn't make sense to me, since there is no paper present, so isn't the 5th bit needs to be 1? I am confused with this response. Or else am I reading this the wrong way?
