### ISSUE TITLE
£ sign within text string

### ISSUE THREAD

**Issue by ac1234** [python-escpos/python-escpos#144]
### Device info
 **Printer:** Epsom TM T88II
Could you advise how you print a '£' sign within text.
Epsom.text('£ 125.00')

**Comment by patkan** [comment]
Hi, thank you for your question.
Have you tried using the `charcode()`-function? I just tested it with the following code:
```python
from escpos.printer import Serial
p = Serial(devfile="/dev/ttyUSB0", baudrate=19200)
text = "£\n"
p.charcode("MULTILINGUAL")
p.text(text)
```
Some codepages might be faulty but at least MULTILINGUAL seems to be correct. (I assume these have to be reviewed and fixed if necessary)
The idea is that input is always unicode and output gets encoded automatically after setting the correct codepage.

**Comment by patkan** [comment]
@ac1234 Has this solved your problem? Do you need any further help?

**Comment by ac1234** [comment]
Thank you for your reply, I have tried several options but with no success.
`#!/usr/bin/python
# -*- coding:utf-8 -*-
'''from escpos import *
p = printer.File("/dev/ttyS0")
text = "£\n"
p.charcode("MULTILINGUAL")
p.text(text)
p.cut()'''

from escpos.printer import Serial
p = Serial(devfile="/dev/ttyS0")
text = "£\n"
p.charcode("MULTILINGUAL")
p.text(text)
p.cut()`

The printer prints 'TU' or I get unicode errors, Thanks

**Comment by miracle2k** [comment]
I have a TM T88IIIP and I cannot get the Euro sign to print.

After some investigation, I think the problem here is that the charcode map in python-escpos is pretty wrong.

The reference in constants.py links to this document: http://www.novopos.ch/client/EPSON/TM-T20/TM-T20_eng_qr.pdf

It mentions that the EUR/PC858 charset, which contains the euro symbol, is decimal 19, or hex ``\x13``. In constants.py it is defined as "\x14".

Now, the php-escpos project defines the charcode tables in profiles; maybe there is a reason for this, and some printers use different mappings.

**Comment by patkan** [comment]
@miracle2k Thanks for the investigation. Do you know the epson online documentation? (https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=2) It would be interesting to compare it with other ones. Apart from that the charcode-table is probably really messed up. I tried to patch it a bit, but simply did not have the time yet to do it properly.

**Comment by miracle2k** [comment]
I think we can close this, now that we have MagicEncode.
