### ISSUE TITLE
Refactor tests

### ISSUE THREAD

**Issue by miracle2k** [python-escpos/python-escpos#167]
I would like to do two things to improve the tests:
- [ ]  Convert to py.test. It would allow us to use the pytest fixture system, which is much less verbose than setup/teardown.
- [ ] Test using the dummy printer. That's faster and less complicated than comparing file outputs.

**Comment by patkan** [comment]
From my point: you are very welcome to do that. I chose nose because I was not familiar with pytest at that moment. However, pytest seems to be the better option in the long run (nose is discontinued in that form, pytest seems to be the "standard"...)
I think the project would benefit from a unified testing setup.

The dummy-printer came after a good part of the tests was written that's why it is not included everywhere. Using only dummy-printer would also have the benefit that we could use detox for testing.

**Comment by patkan** [comment]
732f2dd adds Dummy() for most of the tests.

**Comment by MicroJoe** [comment]
What is the status of this?

I searched `unittest` but nothing matches in the repository so I guess the refactoring was done. Tests are using the Dummy too.

**Comment by patkan** [comment]
I am not sure, I think there was one test left without Dummy, but I haven't checked.

**Comment by patkan** [comment]
Seems like I cleaned up all tests in 5bf26367538f9ffb572659b3c49582aa29dbff2a.
As for the tests, they are written in a mixture of pytest and nose1. The test-runner is pytest. I think it is not really worth the time to rewrite the old tests. We should just encourage new tests not to be dependant on nose.
If somebody is interested, feel free to rewrite the old ones, otherwise I would just close this issue.

**Comment by MicroJoe** [comment]
Agreed for me. We should just use pytest for the new ones and maybe refactor old tests during a rainy weekend if nothing better to do.

**Comment by patkan** [comment]
OK, I will close this now and if someone has the time and motivation the old tests can be rewritten. If not this should not be any problem...

**Comment by patkan** [comment]
We have to reopen this issue. I have overlooked the file-tests in test_cli.py. This is also a bit more nasty to refactor. Maybe instead of not using file we could use unique filenames (in order to allow detox-runs)
