### ISSUE TITLE
Change the license?

### ISSUE THREAD

**Issue by patkan** [python-escpos/python-escpos#171]
Do we want to change the license of this project?
I am not sure whether GPL really fits Python libraries. @miracle2k also said he is not happy with that license. (Why?)

Apart from that the project fork by @mosquito had the LGPL and some similar projects have chosen MIT iirc.

We could license with PSFL. PSFL is BSD-style and GPL-compatible (however without copyleft). Another option would be MIT in my eyes.
All of this would however require that we get consent from every contributor, especially @manpaz. When I took over the development from @manpaz I promised him that this project will stay Open Source and I hold of course onto my word.

**Comment by patkan** [comment]
What does @python-escpos/dev think?

**Comment by mike42** [comment]
I'm happy for [my contributions](https://github.com/python-escpos/python-escpos/commits?author=mike42) to python-escpos to date to be re-licensed under the terms of the MIT License or LGPL v3+. I've used the MIT license for most of my original work on GitHub, so I'm already sold on permissive licensing and open to suggestions.

I've never seen a project that uses PSFL though, is it common? The terms are fine, but it's project-specific and listed as ['non-reusable'](https://opensource.org/proliferation-report) by OSI, meaning "specific to their authors and cannot be reused by others", which is why I ask.

**Comment by miracle2k** [comment]
I prefer MIT/BSD.  I think LGPL is fine. I don't like GPL for libraries (application yes) because it prevents people from contributing that don't want to open up their application source.

**Comment by patkan** [comment]
PSFL is used by some Python-libs. However, the "non-reusable" makes it for me unusable. I did not know that one.
Then I would also prefer MIT. My opinion is similar to that of @miracle2k. In an application GPL is good, but for libraries (especially this one) it is not that practicable.
OK, I will leave this a bit open if anyone wants to give input. After that I will mail all contributors and ask them whether MIT would be OK for them.

**Comment by DavisGoglin** [comment]
I'm open to any of the above mentioned licenses for my contributions to this project.

**Comment by thijstriemstra** [comment]
+1 MIT

**Comment by manpaz** [comment]
MIT or LGPL are both fine.

**Comment by noio** [comment]
Totally OK with license change! Thanks for the ping.

**Comment by ssokolow** [comment]
I have no problem with an MIT license.

**Comment by patkan** [comment]
@inversesandwich @belono I can't reach you otherwise. Is this change from GPL to MIT OK for you? You can also answer me via mail (dev[at]pkanzler.de) if you don't want to post here.

**Comment by zouppen** [comment]
I'd prefer LGPLv3 but my contribution is quite small so feel free to pick any.

**Comment by braveheuel** [comment]
For me MIT is ok!

**Comment by belono** [comment]
MIT is ok for me, too.
