### ISSUE TITLE
ideas for api changes

### ISSUE THREAD

**Issue by patkan** [python-escpos/python-escpos#176]
Hi,
we will soon be releasing version 3. Which aspects of the API should be changed until then and how?

**Comment by miracle2k** [comment]
The capabilities patch already contained an API change - the constructor no longer takes the number of profiles.

Personally, I would take more time to collect a bunch of API changes and then release.

**Comment by patkan** [comment]
Jep, me too. I just wanted to collect what has to be done.
I think we definitely have to improve set().

Apart from that I would like to improve the style of parameters. Currently we have method-parameters like `type="BOLD"`. I would prefer something like `type=texttype.bold `. In order to make it somewhat compatible we could set `texttype.bold="BOLD"`. This way we can do string comparison and even catch the old parameters.

And maybe we can find a clean structure that when you do `import escpos` you get everything what you need for using python-escpos.

**Comment by mike42** [comment]
I agree with the issues with `set()` noted above.

Would you consider an implementation which separates `set()` into small single-purpose methods, uses something other than string literals as arguments, and provides a replacement `set()` to maintain some continuity?

Eg, maybe the syntax is off, but to illustrate in code:

```python
class FontUnderline:
      None, Single, Double = range(3)

class FontWeight:
      None, Bold = range(2)
```

```python
class Printer:
...
    def setUnderline(underline=FontUnderline.None):
...
    def setWeight(weight=FontWeight.Normal):
...
    def set(**kwargs):
        # Just read arguments and delegate
...
```

And the user can still:

```python
foo.set(weight=FontWeight.Bold, underline=FontUnderline.Double)
```

Or..

```python
foo.setWeight(FontWeight.Normal)
```

This could help keep complexity down so that `set` doesn't get out of hand as more features are added.

**Comment by miracle2k** [comment]
My thoughts: 

- I'm not a fan of a ``set(type=TextType.Bold)``-style API. That's a Java-ism to me. There isn't any benefit in Python compared to a string: ``set(type="bold")``. Only now I have to import extra types (and google the naming of TextType).

- I do like staying close to raw ESC/POS. The `text_type` argument we currently have is our own invention, I don't see the need for that. Just let the user set "bold" and "underline" separately.

- I like simplicity. Boldness is a boolean, so I would suggest `set_bold(True)`. If the term used were "weight", I would still prefer ``set_weight("bold")``. For underline, which has single and double options, I would support: ``set_underline(True|False|single|double)``. 

- I like separating set() into distinct methods. I should be able to set the boldness without affecting the font.

- I also like to have a generic ``set()``method, because it can be used with kwargs. But I've been wondering if that ``set()`` should have any defaults, or if it only should write those commands that the user requested. 

   I get why ``set()`` tries to reset all other properties to defaults. But it's not clear why for example the line spacing would not be reset. I.e. what belongs inside set() and what doesn't? It might also be confusing. When I first started, I knew that an empty ``set()`` call is some kind of "reset", but I didn't know it's just python-escpos own idea of a reset.

  Basically, this is about whether we want our API to just map to a raw ESC/POS command, or whether we want the API to have aspects of a layout engine that executes ESC/POS commands for you.

   The second thing is certainly useful. I wonder if that, we could come up with something different entirely. Just some spontaneous ideas:
     - Like MagicEncode, we keeps track of state. If I call ``magic_set(bold=True)`` and then ``magic_set()``, the only command executed the second time is ``turning of bold``.
     - Even without tracking state, we could do: 
```python
         engine = LayoutEngine(printer_driver, defaults={bold: True, width=4, font=a}}); 

         # set everything to the default, except weight
         engine.set(weight=2)  

         # change the defaults for this block
         with engine.block(vertical_spacing=2) as block:  
             block.set(bold=True)
             block.text("this text is bold")
             block.set(underline=True)
             block.text("this text is underlined but not bold")

         # another API idea
         engine.text("this text is bold", bold=True)  
         engine.text("this text is underlined but not bold", underline=True)        
```
    
This way we have both; a low-level API where I can send ESC/POS commands without any magic (but with nice names), and an API that makes it easier to assemble the style changes I want to make for every line.

The high-level API may also provide things such as ``hr()`` to output a line that matches the column width. I'm also working on https://github.com/miracle2k/py-xml-escpos as an even higher-level construct, but some of the logic (like aligning text both left and right in the same line) are not just useful via XML; they could also be useful in code, e.g, say:

```
layout_engine.line(left="foo", right="foo")
layout_engine.columns("left", "center", "right")
```

**Comment by miracle2k** [comment]
I'd like to make a concrete API suggestion, based on what I wrote above, and would like to hear eveyrone's thoughts.

```python
# We can send explicit ESC/POS commands:
>>> printer = Stdout()

>>> printer.set()
(no output)

>>> printer.set(underline='single')
(ESC+underline_single)

>>> printer.set_underline('double')
(ESC+underline_double)
```

But we also have a high-level API:

```python
# I want to use the b font by default:
printer = Usb(default_layout={font: "b"})

# This is like the old set() method. It resets everything to ``default_layout + overwrites``.
printer.layout(bold=True)

# We can use a context manager to make this even nicer:
with printer.layout(bold=True):
    printer.text("this will be bold")
printer.text("this will not be bold")
```

Now we satisfy both use-cases. We have a low-level API for people who want to be explicit about what commands to send. And we have higher-level that requires less code for resetting the styles.

**Comment by mike42** [comment]
I like this syntax, and it leaves room to patch in the 'page mode' commands later without breaking backwards compatibility, too.

I'll be happy to compromise on the use of strings instead of constants if this is common in the python world. Auto-complete is my only real rationale.

![image](https://cloud.githubusercontent.com/assets/2080552/18471903/5ede312e-79f7-11e6-82b9-1ac598d7b417.png)

Very minor, but I would also like to edit the `qr()` function to have an `impl` argument (just like `image()` does), instead of the `native` argument that it has now. This is just for consistency.

**Comment by patkan** [comment]
In Python-APIs I have seen both. String-literals as parameters and classes. But I see the point that @miracle2k has. I think probably the best way would be refactoring the API so that we mostly have boolean properties. (Many parameters can be in fact boolean)

@miracle2k, I also like your proposal. I know this is just an example but just so I get it right: You propose removing all layout-ish functionalities from the API like we have it now and move it into an higher level-API. Would you then make things like the MagicEncode also available in the lower level API or would you put there only the code for issuing the codepage-switching. The higher level API could then use that for the MagicEncode-feature.

**Comment by miracle2k** [comment]
@patkan Originally I thought about having a separate "LayoutEngine" class. But in my last proposal I changed my mind; it shouldn't be too complicated for the user. The ``Engine`` object should have the ``layout()`` method. Now if internally it should be implemented via it's own class I'm not sure; we might know more when implementing.

@mike42 I'm not sure about what auto-complete in the Python world can do these days. But if an autocompleter could be made to understand that the `underline` parameter is of type `FontUnderline`, I hope it could also understand that it supports the string values "double" or "single".  But I might be wrong about that.

**Comment by mike42** [comment]
For auto-complete, the `bpython` (and `bython3`) interpreter is probably the best I've seen. Using python-escpos in this is a worthwhile exercise in my opinion, as long as you can install it for your platform and you have a few minutes to spare (`apt-get install bpython3` in Debian/Ubuntu)

I'm going to mention #183. The `control()` method seems very low-level, and I think we should consider replacing/removing it. Eg, we can add `feed()` and `formFeed()` as their own methods, implementing `LF`/`ESC d` and `FF` respectively. (Does anyone have a printer that understands vertical tabs?)

**Comment by blaggacao** [comment]
@miracle2k @patkan Wouldn't it be eligible to consider incorporating `py-xml-escpos` directly within `python-escpos`. I'm suggesting this for a very practical selfish reason: If I wasn't digging about 2 full days on escpos, and wondering about some code similarities in the odoo codebase wich triggered my criminalistic instincts, I just wouldn't have found it.
I even almost started on reinventing the wheel it again myself.

**Comment by kleinesfilmroellchen** [comment]
Also see #358 , where I propose an API change for dealing with encodings.

**Comment by kleinesfilmroellchen** [comment]
Anyways, my thoughts on the proposals:

Very great. I think one of the main problems with python-escpos is not that it doesn't work (it does so wonderfully and consistently), but that the API is unintuitive and partially unpythonic.

String parameters are always the better option over enum parameters, but booleans are, of course, best, if possible.

I would prefer the splitting of `set()` into multiple functions.

Integrating py-xml-escpos into this library would be great. I would imagine a `layout` master class with such API:
```python
# layout is a class in the escpos package, even if it was defined in another file
from escpos import layout

# create a new layout
mylayout = layout()
# various alternative from_ constructors
xml_layout = layout.from_xml('filename or existing xml object')

# methods e.g.
xml_layout.append(pre_created_element_object)
xml_layout.append('simple text paragraph')
xml_layout.append(other_layout_as_nested_element)
xml_layout.append(layout.CONSTANT) # e.g. CUT, CASHDRAW

# use the layout on some printer
printer = # whatever
printer.print_layout(xml_layout)
```

The idea is that `layout` is a class with some internal structure representing the layout, and it can be loaded from an xml file or possibly even other file types (html, markdown) or sources (tcp stream, bluetooth). It is possible to modify and nest layouts however the user wants to, and print them on a printer with a single method that reads in the layout and converts it to ESCPOS commands.

Also, another idea was using the layout as a method of defining formatting. I would use another class capable of context managing for that, possibly named `escpos.format`.

**Comment by kleinesfilmroellchen** [comment]
> ```python
> # We can send explicit ESC/POS commands:
> >>> printer = Stdout()
> 
> >>> printer.set()
> (no output)
> 
> >>> printer.set(underline='single')
> (ESC+underline_single)
> 
> >>> printer.set_underline('double')
> (ESC+underline_double)
> ```

I would prefer to make the first API (`set`with kwargs) set everything else to default values, while the second API does only set the specified parameter (in this case underline). Calling `set` without arguments as a resetter, in my opinion, is unintuitive and should be forbidden in favor of an explicit `reset` method. Maybe even some functionality to _define_ these defaults that `reset` uses.

**Comment by patkan** [comment]
concrete changes for set have been put into another issue, otherwise I would keep this issue as an idea-collection
