### ISSUE TITLE
Cant print barcodes but demo works fine?

### ISSUE THREAD

**Issue by vekexasia** [python-escpos/python-escpos#211]
Hello i think i misunderstood how to use the library (and/or) python. 
When using the demo cli command everything works fine and barcodes are getting printed but when i try to run this little snippet of code it does just write nonsense or `12345678911`:

```python
"""Prints code page tables.
"""

from __future__ import print_function

import six
import sys

from escpos import printer
from escpos.constants import HW_RESET, HW_INIT


def main():
    p = printer.File(devfile="/dev/usb/lp0")
    p.hw(HW_RESET)
    p.hw(HW_INIT)
    p.barcode("12345678911", "UPC-A", function_type="A")
    
    print("CIAO")


main()

```

Not sure i'm using HW_RESET & init correctly.

**Comment by patkan** [comment]
Thank you for your issue. You should not need the `hw`-function and it is not quite correct. The right usage would be `hw('INIT')` as stated here https://python-escpos.readthedocs.io/en/latest/api/escpos.html#escpos.escpos.Escpos.hw

Apart from that UPC-barcodes are a bit more difficult, since they are easy to get wrong (the Wikipedia article helped me a lot with them).

In this case however the problem might be a missing newline or cut. Most printers do nothing until you have a complete line. Try a `text("\n")` at the end of your code.
