### ISSUE TITLE
TypeError: set() got an unexpected keyword argument 'bold' / 'underline'

### ISSUE THREAD

**Issue by KlustoR** [python-escpos/python-escpos#232]
I have:
- [x] searched open and closed issues for duplicates

### Bug description
When i try to use set for bold or underline i get a TypeError "TypeError: set() got an unexpected keyword argument 'bold'"

I have tried with version 2.x from pip install python-escpos,
and have tried with pypi 3.0a0 .tar.gz source (after removing 2.x with pip uninstall python-escpos

### Steps to reproduce
- p.set(bold=True)

### Device info
 **Printer:**  p = printer.File("/dev/usb/lp0")
 **python-escpos version:** 3.0a0
 **python version:** 2.7
 **operating system:** raspbian

**Comment by patkan** [comment]
We had recently a small change in API (it is still unstable for v3, that's why there are only alpha releases)
The change occured in a16d6bde060bcde53f3be2aa9bf5ab30ebf4c28a.

For your use-case please refer to the documentation of a released version: http://python-escpos.readthedocs.io/en/v3.0a1/api/escpos.html
With your version setting `text_type='B'` should work.
Sorry, for the inconvenience and thank you for the report! Feel free to reopen the issue if there is any question left.
