### ISSUE TITLE
Image Encoding 

### ISSUE THREAD

**Issue by MeritEhab** [python-escpos/python-escpos#304]
Hello,
I have a problem with image encoding,
I originally used the escpos package for golang by [kenshaw](https://github.com/kenshaw/escpos) which was developed on behalf of your php code and it didn't have image printing 

I forked the repo and did some job for the image printing you can find it [here](https://github.com/CloudInn/escpos) in the [escpos.go](https://github.com/CloudInn/escpos/blob/master/escpos.go) file and it was relly fine with the Eposn printer that I tested on it

However when Ichanged the printer to SPRT the SP-POS88VMF model to be specific it printed the image as weird characters I tried to print the image as bytes but it ended in the same way 

After that I  tried your python escpos and it printed perfectly on both the printer Epson and SPRT , I tried to go on behalf of the python code on the golang code but Iended up with no result and Idon't know if the pilow library has something to do with the image before printing

So I was asking you if you can help or have any ideas/suggestions that could help me in this issue

Thanks in advance

**Comment by mike42** [comment]
Hello. I contributed the raster image handling implementations that are currently being used in [escpos-php](https://github.com/mike42) and [python-escpos](https://github.com/python-escpos/python-escpos).

Since this is not a `python-escpos` issue, could you make a thread on the issue tracker for the repo that needs the improvements and link to it? I think that watchers of this repo will appreciate it if we take this discussion to the right place, and close this issue off.

I also need the `escpos` project to acknowledge the provenance of its code in its copyright notice. The project is [already using an image implementation which is derived from my work](https://github.com/kenshaw/escpos/blob/master/escpos.go#L538), but this is not apparent from the docs (the link contains `escpos-php` code in comments above corresponding Go code). Licensing issues aside, it is poor form to not provide attribution for ported code.

Once you get these fixed up, I'd be happy to discuss.

**Comment by MeritEhab** [comment]
Hi,
Thanks for fast replying
About making a thread in the needed repo , well Cloudinn forked the repo from kenshaw to do some enhancement and  a contributer in kenshaw's repo was not interested in the enhancement saying it's out of the project scope
So mainly we are not involved with kenshaw anymore we forked the repo and trying to do some enhancement on it which includes the image printing part which is not going well

About your credits I did mentioned that the golang escpos was developed on behalf of your escpos-php repo 
And sure we are going to give you the credit in our documentation for the forked repo
So do you need me to open a thread on my forked repo of kenshaw o rwe are going to continue discussing here

**Comment by patkan** [comment]
@MeritEhab thank you for the issue. As @mike42 wrote, it is more appropriate to create an issue in the repo that should be improved. (This especially helps the other project in tracking the changes)

So I am closing this issue here. Feel free to post a link to the follow up repo that you are opening so people know where to go.

**Comment by thelinuxer** [comment]
Hi,

Just wanted to mention that proper credit was given in our forked [repo](https://github.com/CloudInn/escpos). Thanks for the excellent work.
