### ISSUE TITLE
Can't print on windows

### ISSUE THREAD

**Issue by jongord** [python-escpos/python-escpos#306]
anyone get this working on windows 10?
have it working perfectly on linux ubuntu
have a tm-t88iii model m129c and getting error

            from escpos.printer import Usb
            p = Usb(0x04b8,0x0202,0)
            Traceback (most recent call last):
            File "", line 1, in
            File "C:\Python36\lib\site-packages\escpos\printer.py", line 51, in init
            self.open()
            File "C:\Python36\lib\site-packages\escpos\printer.py", line 57, in open
            raise USBNotFoundError("Device not found or cable not plugged in.")
            escpos.exceptions.USBNotFoundError: USB device not found

Thanks,

Johnny

**Comment by mike42** [comment]
This library uses pyusb, which in turn uses libusb.

A web search suggests that there is some extra setup on Windows, not specific to python-escpos, that you need to do before libusb can see each device.

I'm also a linix user, so that's just about all I've got. I don't expect that we will try to duplicate the documentation of other projects, so if you find a good guide for pyusb on Windows, please drop us a link so that it can be referenced from the docs.
