### ISSUE TITLE
Printer inactive / not printing

### ISSUE THREAD

**Issue by dimitarsh1** [python-escpos/python-escpos#368]
I have:
- [x ] searched open and closed issues for duplicates

### Bug description
Simply, the printer does not print when the command is issued. 
Neither it cuts.

I assume it is related to CUPS but have no idea how to solve it.

### Steps to reproduce
- attach my printer using usb (can print a any file)
- use the default code: 
from escpos.printer import Usb
printer = Usb(idVendor=0x0519, idProduct=0x0003, in_ep=0x81, out_ep=0x02)
printer.text('Print this line, please\n')
printer.cut()

### Device info

 **Printer:** Star TSP100 III futurePRNT eco

 **python-escpos version:** 3.0a6
(but I tried earlier and older as well, same outcome)

 **python version:** 3.7.3

 **operating system:**
Debian 10

**Comment by dimitarsh1** [comment]
@belono 
Yes, correct. I can even use pycups from inside python to send any file to be printed. 
But not via escpos.

**Comment by dimitarsh1** [comment]
Hi Belono, 

Nope, this didn't work either. It creates a job for the printer, but no text is sent. This, I connect to the printer and I send a job, but it is empty. 

![image](https://user-images.githubusercontent.com/15775250/68024351-ca91d580-fca1-11e9-8541-08be3a6f4f1d.png)

Any ideas?

**Comment by belono** [comment]
Ummm, the printer status is Withheld.
Is the user a member of the lpadmin group?
Try to run the print script as root.

**Comment by belono** [comment]
I'm going back to the initial problem to avoid off topic.

If you still want to try the experimental python-escpos CUPS connection, I invite you to continue this conversation in #348. This is a very, very early feature and we will be able to print via CUPS, either using pycups (preferred way) or command line lp in short time.

Nevertheless, if you want to direct print via python-escpos USB connection, I guess you need to delete the printer in CUPS administration, since the USB device is in use by CUPS.
