### ISSUE TITLE
Printing any special characters prints garbage

### ISSUE THREAD

**Issue by cafeoh** [python-escpos/python-escpos#369]
### Steps to reproduce
- Connect an Epson TM-T88V by usb to a raspberry PI 3.
- Send every character from 0-255 with charcode `USA` (optionally force the codepage to `cp437`)
- Get some garbage printed behind each character after 127 (`0x7F`)

### Device info

 **Printer:** Epson TM-T88V
 **Machine:** Raspberry PI 3
 **python-escpos version:** 2.2.0
 **python version:** 3.7.3 32-bit
 **operating system:** Raspbian GNU/Linux 10 (buster)

#### Code needed to reproduce:
```python
p = Usb(0x04b8, 0x0202, 0)
outS = ""
for i in range(30,255):
    outS += chr(i) + "({:d}) ".format(i)

p.charcode("USA")
p.codepage = 'cp437'
p.text("\x1b@")
p.text(outS)
p.cut()
```

#### Picture of the issue: 
![Photo of the printed ticket](https://i.imgur.com/NfX7J2s.png)

Essentially what I'm trying to do is print those box drawing characters to format some info, but I've been unable to do so (not without the extra garbage behind). Trying to print a regular python string directly fails, since it seems like it tries to print the UTF-8 data directly (and therefore creates even more garbage characters)...

**Comment by patkan** [comment]
You could try to use the pre-release  of version 3 that tries to do the codepage-selection automatically.

**Comment by blinxe** [comment]
Hello,

I had the exact same issue on a different configuration (irrelevant, but here goes: HOP-H58 printer, Windows 10 + libusb-win32, Python-3.8.2).
After looking up the code, I saw that the text() method simply calls encode() on its string argument before sending it through the USB backend. If the codepage is set, it is passed as a parameter to encode(), otherwise UTF-8 is used.

I'm not too familiar with the encoding stuff in Python, so I [RTFM](https://docs.python.org/3/howto/unicode.html) and found the cues I needed.
Python strings are sequences of Unicode characters. So for `i==203` for example, the string made up of `chr(203)` refers to the character at codepoint 203 in Unicode (which is Ë, nickname U+00CB). The `text()` method calls `encode()` to transform this into a sequence of bytes. The default (UTF-8) encoding for codepoint U+00CB is [0xC3, 0x8B] (see this [helpful tool](http://www.ltg.ed.ac.uk/~richard/utf-8.cgi?input=203&mode=decimal)). So these are the bytes actually sent to the printer. The printer then interprets them as 2 separate characters from its cp437 codepage, and prints \xC3 as `├` followed by \x8B as `ï`, producing the garbage you see.
If you set the codepage to cp437 beforehand, the `encode()` method will raise a `UnicodeEncodeError` since the 'Ë' character does not exist in this codepage.

So in order to get the printer to produce the expected character (i.e. character 0xCB (203) from cp437: `╦`), you need to call text() with the Unicode codepoint of the character you want. In this example, p.text('\uC38B'), or since Python allows it, p.text('╦').
Once this (Unicode) string is encoded with cp437, the resulting byte sequence will be [0xCB] and the printer will produce the correct glyph.

So in my opinion this is not an issue with python-escpos, although an additional method to send directly the bytes we want could help when we want to work with the codepage directly. Also, the documentation for `text()` is not very helpful regarding these encoding matters.

It's been a while since the issue was opened, but I hope it helps future readers!

**Comment by bill88t** [comment]
For anybody still having this issue but finding the above explanation too complex:
`myprinterobject._raw(bytes(data, "cp437"))`
With `data` being a `str`.
