### ISSUE TITLE
Customization of font size 

### ISSUE THREAD

**Issue by arossoftware** [python-escpos/python-escpos#383]
Hi 

We are looking for a way to customize the font-size when using this module. Either the font size is too small or too big for us. Everything else is working fine with the receipt printing. We can be contacted here on Github or info@arossoftware.com - Skype: live:.cid.1d262373472f1a37. We would also be willing to pay you to help us understand the changes that needs to be done if it takes more time to explain.  

Thanks, 
Milani

**Comment by kleinesfilmroellchen** [comment]
The font size is determined by both the scaling factor and the actual font used by the printer. Each printer will have its own fonts built-in, but generally, the "A" font, or ESC/POS font 0, is the larger, standard font that every printer needs to have, and the "B" font, or ESC/POS font 1, is the smaller font that many cheaper printers lack.

As far as my experimentation with ESC/POS printer control makes me understand printer text rendering, the fonts used by a printer are **black and white raster images** for each character that the printer can print. This is also the reason why you need to resort to image rendering if the printer doesn't have certain characters. When text is sent to the printer, the printer uses a usually read-only lookup table of some sorts to transform each character into a raster image that is then layout onto the printing surface according to alignment and character spacing rules. If **font scale**, an ESC/POS controllable property for both width and height, is different from 1, the printer will **scale up the raster image for each character without interpolation, just by pixel repetition**. If, for example, the text is scaled in the horizontal direction by the factor `2`, for each pixel in the character's raster image, two pixels will be drawn along the horizontal axis, which will make the text appear stretched twice as wide as its normal size.

The issue here is, and this is not solvable by the programmer using an ESC/POS library, that this scaling occurs without any sort of interpolation and therefore, no fractional scaling factor is possible. Images, for example, can easily be scaled to only be a couple of pixels wider because clever scaling algorithms try to distribute the image data onto the new size.

I do not know your exact application, size requirement or printer model. However, there are some possible ways of changing font sizes that you might have tried or should look into:

1. Use the [`set` method of the printer API](https://python-escpos.readthedocs.io/en/latest/user/methods.html#escpos-class) ([Source code](https://python-escpos.readthedocs.io/en/latest/_modules/escpos/escpos.html#Escpos.set)). This allows you to do said font width and/or height multiplication by integer factors. The downside, of course, is the coarse steps in which fonts can be scaled using this method.
2. Use a font provided by your printer that is either the correct size or can be scaled using method (1) to be of the correct size. A good bet is font "B" / font 1, as it is usually a smaller font which means that it will naturally scale in smaller steps than the larger "A" / 0 font. Font setting is done with the same `set` method.
3. Change the printing density (also with `set`), which *might* scale down all fonts and lets you use methods (1) and (2). I cannot confirm this, as the printers I have used do not support printing density. I would also imagine that the print speed would go down.
4. Pre-generate an image with the exact font and size you need, then use the [`image` method](https://python-escpos.readthedocs.io/en/latest/user/methods.html#escpos-class) along with printer-compatible options. This, of course, is much more involved than just saying `printer.text('hello, world')`. If your text is static and never changes in between prints, you can create any sort of image in any supported format and make the above function load that for you and send it to the printer. If your text is dynamic, you might have to look into the PIL library for generating and manipulating images on-the-fly with code, which I have absolutely no knowledge about, but appears to be very powerful. Of course, these methods are one of the easiest ways of getting anti-aliased fonts because the default fonts cannot anti-alias without scaling.

Hope that helps. Please refer to the maintainers of python-escpos for more detailed information, because this is about as far as my knowledge goes.

Request to the community: Could someone with a printer demonstrate the scaling by printing a couple of test prints with the custom width multipliers? I do not have an ESC/POS printer on hand right now.

**Comment by Bougakov** [comment]
I've solved a similar problem - I wasn't satisfied with the printer's built-in fonts, it also lacked support for non-Latin characters. So instead I render Unicode texts using TrueType fonts as images: https://gist.github.com/Bougakov/cb2501e4ed358873805a861e3c555086
