### ISSUE TITLE
capabilities.json missing in alpha package (3.0a7)

### ISSUE THREAD

**Issue by sajjadaemmi** [python-escpos/python-escpos#391]
install latest alpha build of the library
work in debugging
error when make exe with pyinstaller in raspberry pi

FileNotFoundError: [Errno 2] No such file or directory: '/usr/escpos/capabilities.json'

**Comment by MicroJoe** [comment]
I have had the same problem this morning in development mode because I forgot to initialize the submodule for the capabilites. @patkan it is possible that you made the same mistake as me, forgetting to initialize the submodule before releasing the 3.0a7 version?

**Comment by sajjadaemmi** [comment]
@MicroJoe thanks for reply
i dont understand. can you explane exactly what do i do?

**Comment by patkan** [comment]
@sajjadaemmi we have a file called capabilities.json which comes from https://github.com/receipt-print-hq/escpos-printer-db and is included as a git submodule.
If all ties break, you can add the json somewhere to your file system and pass it on as an environment variable: https://python-escpos.readthedocs.io/en/latest/user/usage.html#advanced-usage-change-capabilities-profile

@MicroJoe I am quite sure, that I have intialized the submodule, however, I made some slight changes. All in all I don't like this feature since it has been introduced. There is something broken with the packaging on some platforms (as I am symlinking it from the submodule into the python module and then hoping that setuptools grabs it). I will see how to rework this properly. (Maybe by implementing a hook in setup.py that moves the file into the package)

**Comment by patkan** [comment]
I just unpacked the 3.07 wheel and the capabilities.json is contained. For the packing process I will make another issue as I will have a look, but I am quite sure, that the json is in the 3.0a7 release.

**Comment by sajjadaemmi** [comment]
@patkan i still dont understand what do you mean

in raspberry pi i use 
`sudo pip3 install python-escpos==3.0a7`

then run pyinstaller for make executable file. and when run file. show this error:
![Capture](https://user-images.githubusercontent.com/42681293/81513237-236eb480-933c-11ea-96c9-baa7acfa0fbc.PNG)

**Comment by patkan** [comment]
What I mean is, that the installed python-escpos should contain the capabilities.json. You could check by having a look in the site-packages directory of your python-distribution or by trying it out in a local python script.

You can find your site-packages by [running `python -m site`](https://stackoverflow.com/questions/122327/how-do-i-find-the-location-of-my-python-site-packages-directory). In there should be a directory escpos and in this directory should be a capabilities.json. If this is the case everything is correct. I am not sure what pyinstaller is doing, maybe it is changing the way that the package is structured.

As mentioned, if your program cannot find the capabilities.json, then you can place it in a directory and set this path through an environment variable. Details on this are in the [linked part of the documentation](https://python-escpos.readthedocs.io/en/latest/user/usage.html#advanced-usage-change-capabilities-profile).

**Comment by sajjadaemmi** [comment]
Can you do what I did?
it helps to find the bug Sooner

**Comment by patkan** [comment]
I am sorry, but I do not have the time to debug your pyinstaller setup. I am quite sure that the 3.0a7 should include the `capabilities.json` which is missing in the pyinstaller output that you sent. I am happy to search for the issue if you can show me, that this file is in fact really missing in the wheel install. (I checked on my system and there it is installed)

I am assuming that it might be an issue with pyinstaller not grabbing up the data file. I had a glimpse into the documentation of pyinstaller and it seems possible to explicitly mention data-files in order for pyinstaller to include it.

If you want to try an easier way, you can, as I said, set an environment variable pointing to a capabilities.json (like https://github.com/receipt-print-hq/escpos-printer-db/blob/3b5b35cfd35d297f9085ec16d47d1f77c3f1e768/dist/capabilities.json)

Apart from that I have created #397 which uses `pkg_resources` for retrieving this file. According to the documentation this should be more robust than searching for the file in the installation (as it is down at the moment). It might be the case that pyinstaller can handle this better.
I have created a wheel from the development version in #397:
[python_escpos-3.0a8.dev19+gb9e3827-py3-none-any.whl.zip](https://github.com/python-escpos/python-escpos/files/4612115/python_escpos-3.0a8.dev19%2Bgb9e3827-py3-none-any.whl.zip)
If you download this file, remove the `.zip` file-ending (I just added it in order to upload it here) and install it with pip you can directly check it without waiting for a release of a new version.

**Comment by patkan** [comment]
Hi @sajjadaemmi, not sure if you have seen it, but a new version of the package is released since some time. It changes the way the json is referenced, and maybe your installer package can grab this more easily.

**Comment by patkan** [comment]
As there is a new release that might be fixing this issue, I am closing it. Feel free to open a new issue referencing this one, if it persists in the new release.

**Comment by sajjadaemmi** [comment]
@patkan no new release founded!

**Comment by patkan** [comment]
@sajjadaemmi Please check again, on PyPi you can find https://pypi.org/project/python-escpos/3.0a8/ That is the one that I have mentioned in May.
