### ISSUE TITLE
No responding action (printing, ...Etc)

### ISSUE THREAD

**Issue by pisua** [python-escpos/python-escpos#415]
Hi,
i'm using the lib version 3.0a9.dev26+g84a97e5-py3.6.egg. And i have the same kind of issue using a PL2303 USB to Serial port Adapter.
In my case even if the is_online() methoid return correctly True, when i use another method like text to send a string. Nothing happens and no error is return.

Do you have any clue to solve my issue ?
I'm connection using this command :

from escpos import *
p = printer.Usb(0x067b,0x2303,None,0,0x83,0x02)
p.text("anefoanefan")

**Comment by patkan** [comment]
If you want to be complete sure, that you are actually sending something, you could connect a serial adapter to your serial adapter and listen to it with a terminal program.

Otherwise make sure that your printer is actually capable of understanding escpos and on some printers you have to send a newline before anything happens.

Does any of the older versions work for you? (Just to make sure that this is not a regression in the library)

**Comment by pisua** [comment]
hi i found a solution to interact with the device with this library by asking more information to the provider of the device. thanks for your answer. 
In that case with PL2303 adapter (USB to Serial). we need to use Serial class instead of Usb and connect use the ttyUSB0 and it works.
