### ISSUE TITLE
Separate method open() and constructor

### ISSUE THREAD

**Issue by rsaleev** [python-escpos/python-escpos#445]
### Bug description
Any implementation of retrying algorithm makes code complicated

### Steps to reproduce
i.e. `tenacity` package

In device implementation method open() makes it impossible to implement retrying policy if device is not connected since instance is created after method is called. Don't you think that logic of creating object and connecting to device must be separated? 

In this case there will be no recursion errors and easy implementation than self-made logic 
```
def discover(self):
        while not self.device:
            try:
                self.device = Usb(idVendor=int(os.environ.get('PRINTER_VENDOR_ID'),16),
                                    idProduct=int(os.environ.get('PRINTER_PRODUCT_ID'),16),
                                    in_ep=int(os.environ.get('PRINTER_IN_EP'),16),
                                    out_ep=int(os.environ.get('PRINTER_OUT_EP'),16),
                                    timeout=int(os.environ.get('PRINTER_TIMEOUT')))
                return self.device
            except Exception as e:
                logger.error({'message':repr(e)})
                time.sleep(0.5)
                continue
```
Expected 
```
class MyUsbPrinter(Usb):
    def __init__(self):
       super().__init__(idVendor=int(os.environ.get('PRINTER_VENDOR_ID'),16),
                                    idProduct=int(os.environ.get('PRINTER_PRODUCT_ID'),16),
                                    in_ep=int(os.environ.get('PRINTER_IN_EP'),16),
                                    out_ep=int(os.environ.get('PRINTER_OUT_EP'),16),
                                    timeout=int(os.environ.get('PRINTER_TIMEOUT')))
    def connect(self):
        r = retry(**kwargs) 
        usb_args = {}
        usb_args['idVendor'] = self.idVendor
        usb_args['idProduct'] = self.idProduct
        r(self.open, usb_args={})(self)

my_printer = MyUsbPrinter()
my_printer.connect()
````
And also can be used as callback for read() and write() operations if connection is down to prevent application break

```
def write(self):
    r = retry(**kwargs, retry_error_callback=self.reconnect(self), retry=retry_if_exception_type(USBError))
    # write to device
   r(self._raw, data, timeout)
````

Discuss if it fits  logic, please. Another way is to implement Usb device without inheritance.

**Comment by drakorg** [comment]
I completely agree. Object creation and possibility to actually connect are two completely different things. printer.Serial has this approach already: if you don't specify the devfile, it doesn't attempt to open anything, so you end up with a valid object, only that it won't be able to connect until you specify the devfile later, and try to open it. 

printer.Usb on the other hand was implemented in a different manner and if you can't connect heads up, you don't even have a valid object to work on or retry anymore. 

Of course you can work around this issue, but it would be better if the classes had more consistency between each other regarding this aspect.

One possible workaround is basically composing, by embedding an Usb instance instead of inhreiting from it, as rsaleev suggested.

Regards.

**Comment by belono** [comment]
I'm currently working on this feature and I think that I will draft a PR in a few days, so @patkan you can assign this issue to me. ;-)
