### ISSUE TITLE
Every print starts with an exclamation point

### ISSUE THREAD

**Issue by bmbejcek** [python-escpos/python-escpos#470]
I have:
- [X] searched open and closed issues for duplicates

### Bug description
Every time I go to print any text or image, it starts off with an exclamation point. This only happens when I call the set() function. When I don't use the set function, it prints as normal. Any helpful hints about where this is being caused in the code?

### Steps to reproduce
from escpos.printer import Usb
p = Usb(0x0416, 0x5011, 0, 0x81, 0x01)
p.set()
p.block_text('Test')

### Device info

 **Printer:** TEROW T5890K

 **python-escpos version:** 2.2.0

 **python version:** 3.5.3

 **operating system:** Linux

**Comment by patkan** [comment]
You could try one of the pre-release versions by installing with `--pre` flag set for pip. (Unfortunately there is not a newer release version as the API is not stable)

Instead of `block_text` you could use the function for text or try out sending directly with `_raw`. This way you can try to rule out any side effects (of maybe misunderstood commands).

Since you wrote that it happens only after calling `set`, you could check the commands that are sent in this function. Could be the case that your printer does not handle something not as expected.

If you find any unsupported commands, feel free to extend your issue here.

**Comment by bmbejcek** [comment]
Thank you! This is really helpful to start debugging. I appreciate it!
