### ISSUE TITLE
how to solve print chinese text garbled by serial in raspi

### ISSUE THREAD

**Issue by mengluo04** [python-escpos/python-escpos#491]
when i print chinese text in my raspi 3 by use serial to print，but print qrcode the result is normal，how to normal it

**Comment by SydneyOwl** [comment]
try using `raw()`:
```python
    escposobject._raw("{}\n".format(txt).encode('GB18030'))
```
you should replace escposobject to proper ones, like `Usb` `network` or sth else.
this encodes chinese characters to GB18030 so my XP58IIH is able to process them.

**Comment by lukaiqi** [comment]
> 

my code like this:
 from escpos.printer import Serial
 p = Serial(devfile='/dev/rfcomm1', baudrate=115200)
p._row("111")
but run error throw error like this
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Serial' object has no attribute '_row'
![image](https://user-images.githubusercontent.com/32565940/186915330-c37ade99-e6bf-4583-b283-367fea83a2b6.png)

**Comment by SydneyOwl** [comment]
not `row`.
it's `raw` 
😂

**Comment by lukaiqi** [comment]
> not `row`. it's `raw` 😂

i change row to raw
it can work
thank you

**Comment by iosc** [comment]
> try using `raw()`:
> 
> ```python
>     escposobject._raw("{}\n".format(txt).encode('GB18030'))
> ```
> 
> you should replace escposobject to proper ones, like `Usb` `network` or sth else. this encodes chinese characters to GB18030 so my XP58IIH is able to process them.

your _raw solution helped me a lot (^_^)

i am printing from my laravel 11 based web app on the internet to my local thermal printer Zywell 808 (built in Simplified Chinese GB18030 resident characters) thermal receipt printer at local network

To be able to print Chinese character i built a python 3 based Kivy as a internet to local network print agent server

I use network_printer._raw(text..encode('GB18030') + b), which the + b is important part because i have the str to bytes error.

Thank you for sharing
