### ISSUE TITLE
Connect over an external network 

### ISSUE THREAD

**Issue by nisargushah** [python-escpos/python-escpos#510]
Is there a way to connect to the printer using this library to connect to the printer from outside the network? 

I want to connect my server to multiple printers over different network.

**Comment by belono** [comment]
Hi @nisargushah 

Alternatively, you can use our (not merged yet) CUPS printer connector at #348 by updating to that PR. 

You can find instructions [there](https://github.com/python-escpos/python-escpos/pull/348) but don't doubt to ask for help if needed.


Hopefully @patkan will merge that feature ASAP since there are many users who find it useful. :-)

**Comment by patkan** [comment]
Hi @belono, thank you for the ping :-)
#348 is ready from your side, correct? The documentation build job and lint is failing, but that is something that I have to fix (among other things), so I would merge if you say it is OK.

**Comment by belono** [comment]
Hi @patkan .

> https://github.com/python-escpos/python-escpos/pull/348 is ready from your side, correct?

> 

Yes, it is.

> The documentation build job and lint is failing

> 
The lint failure is just a pair of newlines located after the definition of the [escpos.soft_barcode](https://github.com/python-escpos/python-escpos/blob/master/src/escpos/escpos.py#L585) and [test_densities](https://github.com/python-escpos/python-escpos/blob/master/test/test_function_set.py#L257) methods that should be removed.
However, the docs build failure is more tricky for me since it seems to fail due to the lack of adding the `pycups` dependency to the build, and that is platform dependent.
