### ISSUE TITLE
Can't initialise printer

### ISSUE THREAD

**Issue by uxwill** [python-escpos/python-escpos#67]
I am a complete noob so please excuse me. I am trying to print using an Epson t70 using the Raspberry Pi.

I followed your tutorial.

But now I’m stuck.

When I try to initialise the printer with:

Epson = printer.Usb(0x04b8,0x0202)

I get the following error:

bash: syntax error near unexpected token ‘(‘

What am I doing wrong?

Your help will be greatly appreciated

**Comment by manpaz** [comment]
Hi @uxwill ,

Seems like you are trying to execute python code in the bash prompt.

In order to interact with the printer you have to write python script. Look at the following example:
https://github.com/manpaz/python-escpos/wiki/Usage#define-your-instance

Thank you for your interest in the project ;)

**Comment by uxwill** [comment]
Hi @manpaz 
Got it to work! thanks for your help and great library. :)

**Comment by manpaz** [comment]
Your very welcome!

On Sun, Nov 22, 2015 at 1:32 AM, uxwill <notifications@github.com> wrote:

> Hi @manpaz <https://github.com/manpaz>
> Got it to work! thanks for your help and great library. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/manpaz/python-escpos/issues/67#issuecomment-158740020>
> .
>



-- 
Manuel F Martinez
Linux Systems Engineer
