### ISSUE TITLE
Feature: Add optional timeout variable for network connections

### ISSUE THREAD

**Issue by Loafdude** [python-escpos/python-escpos#86]
I needed to shorten the timeout for printers to return to the user more quickly.

I'm not familiar with merges etc sorry. Thought I would share maybe make it into dev branch

printer.py line 155

    def __init__(self, host, port=9100, timeout=60, *args, **kwargs):
        """

        :param host : Printer's hostname or IP address
        :param port : Port to write to
        """
        Escpos.__init__(self, *args, **kwargs)
        self.host = host
        self.port = port
        self.timeout = timeout
        self.open()

    def open(self):
        """ Open TCP socket with ``socket``-library and set it as escpos device """
        self.device = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.device.settimeout(self.timeout)
        self.device.connect((self.host, self.port))

        if self.device is None:
            print("Could not open socket for {0}".format(self.host))

**Comment by patkan** [comment]
Thank you for your contribution!
If you want to you can clone the repository and the create a pull request against dev-branch. If you do so please add something like `param timeout: timeout in ?ms? for the socket-library` to the docstring of the `__init__`-method.
Otherwise I could simply add this commit by myself, if it is ok for you. If you want to be credited in the commit you could send me the mail-adress that you use for github to patrick.kanzler{at}fablab.fau.de
